/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Cactoro.gltf -o src/components/Cactoro.jsx -r public 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Cactoro(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Cactoro.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Idle"].reset().fadeIn(0.5).play();
    return () => actions["Idle"].fadeOut(0.5);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh
            name="Cactoro"
            geometry={nodes.Cactoro.geometry}
            material={materials.Atlas}
            skeleton={nodes.Cactoro.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Cactoro.gltf");
